# Device Code Flow

# see https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#get-a-token
# for details


# Tenant htl-villach.at
@tenantId={{$processEnv TENANT_ID}}

# Name of the registered app
@clientId={{$processEnv CLIENT_ID}}

# The credential of the client
@clientCredential={{$processEnv CLIENT_CREDENTIAL}}

# What kind of authorizations are requested?
@scope={{clientId}}/.default profile



### Start Client Credentials flow

# @name authResult
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&scope={{scope}}&client_secret={{clientCredential}}&grant_type=client_credentials


### save response in variables

@accessToken = {{authResult.response.body.$.access_token}}


### Send request to own API using access token

GET http://127.0.0.1:8080/protected
Authorization: Bearer {{accessToken}}

